---
- name: Create '{{ dest }}' directory if it does not exists
  ansible.builtin.file:
    path: '{{ dest }}'
    state: directory
    mode: 0755

- name: Configuring Docker Compose file for {{ service_name }}
  ansible.builtin.copy:
    content: '{{ compose }}'
    dest: '{{ dest }}/docker-compose.yml'
    mode: 0644

- name: Copy files for {{ service_name }}
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ dest }}'
    mode: 0644
  loop: '{{ files }}'

- name: Docker pull images
  ansible.builtin.command:
    cmd: docker compose pull
    chdir: '{{ dest }}'
  register: result
  changed_when: "'Pull complete' in result.stderr | default('')"

- name: Shutdown {{ service_name }} before its up
  ansible.builtin.command:
    cmd: docker compose down --remove-orphans
    chdir: '{{ dest }}'
  register: result
  changed_when: "'Removed' in result.stderr | default('')"
  when: down_before_up | bool

- name: Start/restart {{ service_name }}
  ansible.builtin.command:
    cmd: docker compose up -d --remove-orphans
    chdir: '{{ dest }}'
  register: result
  changed_when: "'Started' in result.stderr | default('')"

- name: Wait {{ service_name }} ready to serve...
  ansible.builtin.wait_for:
    port: '{{ service_port }}'
    delay: 3
    timeout: 60
  when: service_port|int != 0
